# -*- coding: utf-8 -*-
"""exercicios.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YSuYGjSZ8DN6FC1dwLEYEC_j__3hdQOU

## 📌 Tópico: Manipulação de Strings

Este tópico aborda métodos de strings, fatiamento e formatação.

---

### Validador de Email

Crie um programa que valide um endereço de email. O email é válido se:

1. Contém o caractere `@`
2. Termina com `.com` ou `.com.br`
3. Não contém espaços

Solicite o email ao usuário e exiba se é válido ou inválido.
"""

email = input('Digite seu email: ')
fim_1 = email[-4:] == '.com'
fim_2 = email[-7:] == '.com.br'
if '@' in email and (fim_1 or fim_2) and ' ' not in email:
  print('Email válido!')
else:
  print('Email inválido!')

"""### Extraindo Informações de uma String

Dada a string: `"2024-03-15"` (formato de data)

Extraia e exiba:
1. O ano (primeiros 4 caracteres)
2. O mês (caracteres 5 a 7)
3. O dia (últimos 2 caracteres usando índice negativo)
4. A data formatada como DD/MM/AAAA
"""

data = input('Digite uma data na ordem ano, mês e dia AAAA-MM-DD: ')
ano = data[:4]
mes = data[5:7]
dia = data[-2:]
print('Ano: ',ano)
print('Mês: ',mes)
print('Dia: ',dia)
data_formatada = dia + '/' + mes + '/' + ano
print('Data formatada: ',data_formatada)

"""---

### Relatório Formatado com F-Strings

Crie um relatório de vendas formatado usando f-strings com os seguintes dados:

- Nome do produto: "Notebook Gamer"
- Quantidade vendida: 125
- Preço unitário: 3299.99
- Desconto aplicado: 0.15 (15%)
- Total bruto: quantidade × preço
- Total com desconto: total bruto × (1 - desconto)

Exiba um relatório formatado com:
1. Nome do produto centralizado (20 caracteres)
2. Quantidade com preenchimento de zeros (3 dígitos)
3. Preço unitário como moeda (R$ com 2 decimais)
4. Desconto como porcentagem (2 decimais)
5. Total bruto com separador de milhar e 2 decimais
6. Total com desconto com separador de milhar e 2 decimais

**Saída esperada**:
```
========== RELATÓRIO DE VENDAS ==========
Produto:    Notebook Gamer    
Quantidade: 125 unidades
Preço Unit.: R$ 3299.99
Desconto:   15.00%
Total Bruto: R$ 412,498.75
Total Final: R$ 350,123.94
=========================================
```
"""

produto = 'Notebook Gamer'
quantidade = 125
preco = 3299.99
desconto = 0.15
total_bruto = quantidade * preco
total_com_desconto = total_bruto * (1 - desconto)

texto = ' RELATÓRIO DE VENDAS '
print(texto.center(40, '='))
print(f'Produto: {produto:^20}')
print(f'Quantidade: {quantidade:03}')
print(f'Preço Unit.: {preco:.2f}')
print(f'Desconto: {desconto:.2%}')
print(f'Total Bruto: {total_bruto:,.2f}')
print(f'Total Final: {total_com_desconto:,.2f}')
print(40 * '=')

"""---

## 📌 Tópico: Operadores

Este tópico aborda operadores aritméticos, de atribuição, relacionais e lógicos.

---

### Sistema de Validação com Operadores Lógicos

Crie um sistema que valide se uma pessoa pode dirigir baseado nas seguintes condições:

- Idade mínima: 18 anos
- Possui carteira de motorista: True/False
- Não está com a carteira suspensa: True/False

A pessoa pode dirigir se:
- Tiver 18 anos ou mais **E**
- Possuir carteira de motorista **E**
- Não estiver com a carteira suspensa

Solicite as informações ao usuário e exiba se pode ou não dirigir.

**Exemplo de entrada**:
```
Digite sua idade: 25
Possui carteira de motorista? (True/False): True
Está com a carteira suspensa? (True/False): False
```

**Saída esperada**:
```
Pode dirigir!
```
"""

idade = int(input('Digite sua idade: '))
possui_habilitacao = input('Possui habilitação? (True/False) ')
carteira_suspensa = input('Está com a carteira suspensa? (True/False) ')

if idade >= 18 and possui_habilitacao.lower() == 'true' and carteira_suspensa == 'false':
  print('Pode dirigir!')
else:
  print('Você não pode dirigir.')

"""---

### Calculadora de Desconto Progressivo

Crie uma calculadora de desconto que aplica descontos progressivos baseados no valor da compra:

- Compras até R$ 100: sem desconto
- Compras entre R$ 100 e R$ 500: 5% de desconto
- Compras entre R$ 500 e R$ 1000: 10% de desconto
- Compras acima de R$ 1000: 15% de desconto

Além disso, se o cliente for VIP (True/False), adicione 2% de desconto extra.

O programa deve:
1. Solicitar o valor da compra
2. Solicitar se é cliente VIP
3. Calcular o desconto baseado na faixa de valor
4. Adicionar desconto VIP se aplicável
5. Calcular o valor final
6. Exibir: valor original, desconto aplicado (%), valor do desconto (R$), valor final

**Exemplo de entrada**:
```
Digite o valor da compra: R$ 750.00
É cliente VIP? (True/False): True
```

**Saída esperada**:
```
Valor original: R$ 750.00
Desconto aplicado: 12.00%
Valor do desconto: R$ 90.00
Valor final: R$ 660.00
```
"""

valor_compra = float(input('Digite o valor da compra: '))
if valor_compra <= 100:
  desconto = 0.0
elif valor_compra <= 500:
  desconto = 0.05
elif valor_compra <= 1000:
  desconto = 0.1
else:
  desconto = 0.15
vip = input('Você é cliente VIP? (True/False)')
if vip.lower() == 'true':
  desconto += 0.02
valor_final = valor_compra * (1 - desconto)

print(f'Valor original: {valor_compra:.2f}')
print(f'Desconto aplicado: {desconto:.2%}')
print(f'Valor do desconto: {(valor_compra * desconto):.2f}')
print(f'Valor final: {valor_final:.2f}')

"""---

## 📌 Tópico 4: Controle de Fluxo

Este tópico aborda estruturas condicionais, loops FOR e WHILE, e controle avançado.

---

### Validador de Senha com WHILE

Crie um programa que valide uma senha. A senha deve:

- Ter pelo menos 8 caracteres
- Conter pelo menos uma letra maiúscula
- Conter pelo menos uma letra minúscula
- Conter pelo menos um número

O programa deve solicitar a senha repetidamente até que uma senha válida seja fornecida, usando `while`.

**Exemplo de execução**:
```
Digite uma senha: abc
Senha inválida! Tente novamente.
Digite uma senha: senha123
Senha inválida! Tente novamente.
Digite uma senha: Senha123
Senha válida! Cadastro realizado com sucesso.
```
"""

while True:
  senha = input('Digite sua senha: ')
  if len(senha) >= 8 and senha.lower() != senha and senha.upper() != senha and not(senha.isalpha()):
    print('Senha válida! Cadastro realizado com sucesso.')
    break
  print('Senha inválida! Tente novamente.')

"""---

### Menu Interativo com While True

Crie um menu interativo que permite ao usuário:

1. Calcular área de um retângulo
2. Calcular área de um círculo
3. Verificar se um número é par ou ímpar
4. Sair do programa

O programa deve:
- Exibir um menu numerado
- Solicitar a opção do usuário
- Executar a operação escolhida
- Voltar ao menu após cada operação (exceto ao sair)
- Usar `while True` com `break` para sair
- Usar `continue` para voltar ao início do loop em caso de opção inválida

**Exemplo de execução**:
```
=== MENU ===
1. Calcular área do retângulo
2. Calcular área do círculo
3. Verificar se número é par/ímpar
4. Sair
Escolha uma opção: 1
Digite a largura: 5
Digite a altura: 3
Área do retângulo: 15.0

=== MENU ===
...
Escolha uma opção: 4
Programa encerrado. Até logo!
```
"""

texto = ' MENU '
while True:
  print(texto.center(12, '='))
  print('1. Calcular área do retângulo')
  print('2. Calcular área do círculo')
  print('3. Verificar se número é par/ímpar')
  print('4. Sair')
  escolha = int(input('Escolha um opção: '))
  if escolha == 1:
    base = float(input('Digite a base do retângulo: '))
    altura = float(input('Digite a altura do retângulo: '))
    print(f'Área do retângulo: {base * altura}')
    break
  elif escolha == 2:
    raio = float(input('Digite o raio do círculo: '))
    print(f'Área do círculo: {3.14159 * raio**2}')
    break
  elif escolha == 3:
    x = int(input('Digite um número inteiro: '))
    if x % 2 == 0:
      print(f'O número {x} é par.')
    else:
      print(f'O número {x} é ímpar.')
    break
  elif escolha == 4:
    break
  continue
